version: '3.8'

services:
  keycloak:
    container_name: keycloak-bsn
    image: quay.io/keycloak/keycloak:26.0.5
    ports:
      - "8480:8080"
    environment:
      KC_DB: dev-file
      KC_METRICS_ENABLED: "true"
      KC_HEALTH_ENABLED: "true"
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev
    networks:
      - stock-management-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  stock-management-network:
    driver: bridge